### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by cforce** [resilva/Redmine-Fields-permissions#1]
Thanks fo this nice plugin!

Would be very useful if your add some enhancements.

(1) Not just let enable,disbale the 3 fields but all fields except topic and status, especially custom fields.
(2) Be able to enable, disable fields not only dependent on role but on status value too.
(3) Enable, disable and read only as additional switch.

I know there are many feature requests which will be satisfied with this enhancement.

E.g take alook on http://www.redmine.org/issues/8050 and related.

Tx a lot for ur contribution, kepp on!

**Comment by resilva** [comment]
Hi,

Happy if you like it ! You have some interesting ideas and i've already seen the 8050 issues in redmine, but to be honnest at this moment i haven't the time to implement some others option, in the futur i hope i'll have more time to do it anyway. This project is in public so if someone want to contribute it can be pretty good for all ! Anyway i'll try to do my best for continue to update this but not before one month i think.

**Comment by resilva** [comment]
Hi,

Happy if you like it ! You have some interesting ideas and i've already seen the 8050 issues in redmine, but to be honnest at this moment i haven't the time to implement some others option, in the futur i hope i'll have more time to do it anyway. This project is in public so if someone want to contribute it can be pretty good for all ! Anyway i'll try to do my best for continue to update this but not before one month i think.

**Comment by cforce** [comment]
Sure, i understand. 
The redmine community now is waiting for this feature(s) since more than 2 years. Waiting one month in this case is quite ok ;)
If my ror skills would be better i would do i myself, but till now i am only hacking small fixes or optical enhancements.

**Comment by resilva** [comment]
I know, 1 month it's probably the time will i can work on the plugin but to be honest i don't know ror and ruby before making this, so i'm not good at all but i can try if it's can help some peoples :)

**Comment by resilva** [comment]
I know, 1 month it's probably the time will i can work on the plugin but to be honest i don't know ror and ruby before making this, so i'm not good at all but i can try if it's can help some peoples :)
