### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by xaionaro** [resilva/Redmine-Fields-permissions#17]
Can you add a license file? I don't know my permissions on coping/modifing/etc for this plugin.

**Comment by resilva** [comment]
Done, you can clearly do what ever you want with this plugin ;)

**Comment by xaionaro** [comment]
Nothing, yet.))

Just researching a way to hide issue fields for certain role. It may happened that I may want to copy&paste something from your plugin :)

… Sorry for my English…

**Comment by resilva** [comment]
No probs :)

Hope this would help you to do what you want.
