### ISSUE TITLE
This plugin break sub task creation

### ISSUE THREAD

**Issue by ebougerolle** [resilva/Redmine-Fields-permissions#2]
Hi,

Y're plugin break the subtask process.

When creating new subtask a new task is created insta,d of subtask.

Ca confirmed me this issue ?

PS : I've updated your plugin for set priority field permissions.

EB

**Comment by resilva** [comment]
To be honnest i don't really know ruby on rail and ruby so it's possible that the plugin itself was coded badly and i don't know what you want to say by breaking the subtask process. If you can be more clear about that please, might be i can fix it.

Romain

**Comment by xeagle2** [comment]
You use your own field_permissions/app/views/issues/_attributes.rhtml view which is totally different from redmine 1.3.0 original view. There is no container for the sub tasks in your custom view:

```
<% if User.current.allowed_to?(:manage_subtasks, @project) %>
<p id="parent_issue"><%= f.text_field :parent_issue_id, :size => 10 %></p>
<div id="parent_issue_candidates" class="autocomplete"></div>
<%= javascript_tag "observeParentIssueField('#{auto_complete_issues_path(:id => @issue, :project_id => @project) }')" %>
<% end %>
```

Please check your plugin to make sure it is compatible with the latest version of redmine.

**Comment by resilva** [comment]
Thanks a lot, i will work on this when i've some time, if anyone want to contribute don't be afraid to it :)

**Comment by resilva** [comment]
I've looked for this issue and your solution was right xeagle2 i've try and it seems to be nice, ihaven't found other modification in the template between the latest version and mine, i'll commit as soon as possible. Thanks again, for helping me solving this issue :)

**Comment by xeagle2** [comment]
You are welcome. If I had enough time to contribute in source code, I would definitely do this :). First of all is to make a plugin usable! Looking forward for the coming update!

**Comment by resilva** [comment]
Thanks you i've updated just right now, you're welcome to contribute. This plugin was waited by the community it could be more and more usefull :)

Issue closed thanks to all again :)
